import "reflect-metadata";
import { interFont } from "@/lib/constants/constants";
import { TrpcProvider } from "@/lib/trpc/provider";
import { RootProvider } from "fumadocs-ui/provider";
import type { Metadata } from "next";
import React from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en" className="relative">
      <body className={`${interFont.className} antialiased bg-background`}>
        <TrpcProvider>
          <RootProvider>{children}</RootProvider>
        </TrpcProvider>
      </body>
    </html>
  );
}
